# redline_docx.py — generate a real Word document with tracked changes.
#
# Produces genuine Word revision marks (<w:ins>/<w:del>), so the exported
# file opens in Microsoft Word with the changes reviewable via
# Accept/Reject — exactly the redline workflow lawyers already use.
#
# Built with python-docx (MIT) at the OOXML level; the approach follows the
# open-source tracked-changes redlining tools (adeu, legal-redline-tools)
# credited in NOTICE.md.

from datetime import datetime, timezone

from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

REVISION_AUTHOR = "OTG Legal Box"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _plain_run(paragraph, text: str) -> None:
    paragraph.add_run(text)


def _revision_wrapper(tag: str, rev_id: int):
    el = OxmlElement(tag)
    el.set(qn("w:id"), str(rev_id))
    el.set(qn("w:author"), REVISION_AUTHOR)
    el.set(qn("w:date"), _now_iso())
    return el


def _inserted_run(paragraph, text: str, rev_id: int) -> None:
    """<w:ins><w:r><w:t>text</w:t></w:r></w:ins> — shows as an insertion."""
    ins = _revision_wrapper("w:ins", rev_id)
    run = OxmlElement("w:r")
    t = OxmlElement("w:t")
    t.set(qn("xml:space"), "preserve")
    t.text = text
    run.append(t)
    ins.append(run)
    paragraph._p.append(ins)


def _deleted_run(paragraph, text: str, rev_id: int) -> None:
    """<w:del><w:r><w:delText>text</w:delText></w:r></w:del> — a deletion."""
    dele = _revision_wrapper("w:del", rev_id)
    run = OxmlElement("w:r")
    dt = OxmlElement("w:delText")
    dt.set(qn("xml:space"), "preserve")
    dt.text = text
    run.append(dt)
    dele.append(run)
    paragraph._p.append(dele)


def build_tracked_changes_docx(chunks, title: str, out_path: str) -> dict:
    """Write a .docx where diff chunks appear as Word tracked changes.

    chunks: the diff structure produced by /api/redline/compare —
            [{"type": "equal"|"insert"|"delete"|"replace", "text"|"old_text"/"new_text": ...}]
    Returns summary counts.
    """
    doc = Document()
    doc.core_properties.title = title
    doc.core_properties.author = REVISION_AUTHOR

    heading = doc.add_heading(title, level=1)
    heading_note = doc.add_paragraph(
        "Generated by OTG Legal Box — changes below are Word tracked changes "
        "(review with Accept/Reject in Microsoft Word)."
    )
    heading_note.runs[0].italic = True

    rev_id = 1
    counts = {"insertions": 0, "deletions": 0}

    def emit(kind: str, text: str):
        nonlocal rev_id
        # One paragraph per source line keeps the document readable and
        # keeps revision runs small enough for Word to merge sensibly.
        for line in text.splitlines() or [""]:
            p = doc.add_paragraph()
            if kind == "equal":
                _plain_run(p, line)
            elif kind == "insert":
                _inserted_run(p, line, rev_id)
                rev_id += 1
                counts["insertions"] += 1
            elif kind == "delete":
                _deleted_run(p, line, rev_id)
                rev_id += 1
                counts["deletions"] += 1

    for chunk in chunks:
        ctype = chunk.get("type")
        if ctype == "equal":
            emit("equal", chunk.get("text", ""))
        elif ctype == "insert":
            emit("insert", chunk.get("text", ""))
        elif ctype == "delete":
            emit("delete", chunk.get("text", ""))
        elif ctype == "replace":
            emit("delete", chunk.get("old_text", ""))
            emit("insert", chunk.get("new_text", ""))

    doc.save(out_path)
    return counts
